name: lumeleto
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers
      - datasets
      - sentencepiece
      - accelerate
      - huggingface_hub